DESCRIPTION = Electronic Design Automation PnR Research
URL = https://github.com/ikle/eda-pnr-research

LIBNAME	= eda-pnr-research
LIBVER	= 0
LIBREV	= 0.1

DEPENDS = cairo

include make-core.mk

s-path-test: LDFLAGS += -lm
